server:
  port: 6002

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${discovery:localhost}:6001/eureka/
  instance:
    prefer-ip-address: false
    hostname: ${ServiceAddress:localhost}

security:
  basic:
    enabled: false
